src/augprint.c: Comment out unused variable
augprint.c: In function ‘quote_value’:
augprint.c:1254:7: error: variable ‘has_special’ set but not used [-Werror=unused-but-set-variable=]
 1254 |   int has_special=0;
      |       ^~~~~~~~~~~