src/jmt.c: Comment out unused variables
jmt.c: In function 'collect':
jmt.c:1539:19: error: variable 'removed' set but not used [-Werror=unused-but-set-variable=]
 1539 |     size_t count, removed;
      |                   ^~~~~~~
jmt.c:1539:12: error: variable 'count' set but not used [-Werror=unused-but-set-variable=]
 1539 |     size_t count, removed;
      |            ^~~~~